name: dropbox_example
description: Demonstrates how to use the dropbox plugin.
publish_to: 'none'
version: 0.5.1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.3
  path_provider: ^2.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  dropbox_client:
    path: ../

flutter:
  uses-material-design: true
