name: dropbox_client
description: Dropbox client for Flutter. The library supports Android and iOS. Authorization is done through Dropbox app or external web browser.
version: 1.1.0
#author: ChunKoo Park <mix1009@gmail.com>
homepage: https://github.com/mix1009/FlutterDropbox

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mix1009.dropbox
        pluginClass: DropboxPlugin
      ios:
        pluginClass: DropboxPlugin

